---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: project-01
spec:
  host: grafana.paasdc.tz.bayportfinance.com
  port:
    targetPort: 80-80
  to:
    kind: Service
    name: grafana.paasdc.tz.bayportfinance.com
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - conditions:
        - status: 'True'
          type: Admitted
      host: grafana.paasdc.tz.bayportfinance.com
      routerName: router
